const Course = require('../models/courseModel');

/* GET ALL COURSES */
exports.getAllCourses = async (req, res) => {
  try {
    const { schoolId } = req.query;
    let courses;
    
    if (schoolId) {
      courses = await Course.getCoursesBySchoolId(schoolId);
    } else {
      courses = await Course.getAllCoursesWithInternCount();
    }
    
    res.status(200).json({ success: true, data: courses });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Failed to fetch courses' });
  }
};

/* GET SINGLE COURSE */
exports.getCourseById = async (req, res) => {
  try {
    const course = await Course.getCourseByIdWithInternCount(req.params.id);
    if (!course) {
      return res.status(404).json({ success: false, message: 'Course not found' });
    }
    res.status(200).json({ success: true, data: course });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Failed to fetch course' });
  }
};

/* CREATE COURSE */
exports.createCourse = async (req, res) => {
  try {
    const { courseName, abbreviation, schoolId } = req.body;
    
    if (!courseName) {
      return res.status(400).json({ success: false, message: 'Course name is required' });
    }
    
    if (!schoolId) {
      return res.status(400).json({ success: false, message: 'School ID is required' });
    }
    
    // Check for duplicate course with same name in same school
    const isDuplicate = await Course.checkDuplicateByName(courseName, schoolId);
    if (isDuplicate) {
      return res.status(409).json({ success: false, message: 'A course with this name already exists in this school' });
    }
    
    // Create course - id, created_at are auto-generated by database
    const courseId = await Course.createCourse(courseName, abbreviation, schoolId);
    
    res.status(201).json({ success: true, message: 'Course created successfully', data: { id: courseId } });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Failed to create course' });
  }
};

/* UPDATE COURSE */
exports.updateCourse = async (req, res) => {
  try {
    const { courseName, abbreviation } = req.body;
    const id = req.params.id;
    
    if (!courseName) {
      return res.status(400).json({ success: false, message: 'Course name is required' });
    }
    
    // Get current course to check its school
    const currentCourse = await Course.getCourseByIdWithInternCount(id);
    if (!currentCourse) {
      return res.status(404).json({ success: false, message: 'Course not found' });
    }
    
    // Check for duplicate course with same name in same school (excluding current record)
    const isDuplicate = await Course.checkDuplicateByNameExcludingId(courseName, currentCourse.school_id, id);
    if (isDuplicate) {
      return res.status(409).json({ success: false, message: 'A course with this name already exists in this school' });
    }
    
    const affectedRows = await Course.updateCourse(id, courseName, abbreviation);
    
    if (affectedRows === 0) {
      return res.status(404).json({ success: false, message: 'Course not found' });
    }
    
    res.status(200).json({ success: true, message: 'Course updated successfully' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Failed to update course' });
  }
};

/* DELETE COURSE */
exports.deleteCourse = async (req, res) => {
  try {
    const affectedRows = await Course.deleteCourse(req.params.id);
    
    if (affectedRows === 0) {
      return res.status(404).json({ success: false, message: 'Course not found' });
    }
    
    res.status(200).json({ success: true, message: 'Course deleted successfully' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Failed to delete course' });
  }
};
