const School = require('../models/schoolModel');

/* GET ALL SCHOOLS */
exports.getAllSchools = async (req, res) => {
  try {
    const schools = await School.getAllSchools();
    res.status(200).json({ success: true, data: schools });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Failed to fetch schools' });
  }
};

/* GET SINGLE SCHOOL */
exports.getSchoolById = async (req, res) => {
  try {
    const school = await School.getSchoolById(req.params.id);
    if (!school) {
      return res.status(404).json({ success: false, message: 'School not found' });
    }
    res.status(200).json({ success: true, data: school });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Failed to fetch school' });
  }
};

/* CREATE SCHOOL */
exports.createSchool = async (req, res) => {
  try {
    const { schoolName } = req.body;
    
    if (!schoolName) {
      return res.status(400).json({ success: false, message: 'School name is required' });
    }
    
    // Check for duplicate school with same name
    const isDuplicate = await School.checkDuplicateByName(schoolName);
    if (isDuplicate) {
      return res.status(409).json({ success: false, message: 'A school with this name already exists' });
    }
    
    // Create school - id, created_at, updated_at are auto-generated by database
    const schoolId = await School.createSchool(schoolName);
    
    res.status(201).json({ success: true, message: 'School created successfully', data: { id: schoolId } });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Failed to create school' });
  }
};

/* UPDATE SCHOOL */
exports.updateSchool = async (req, res) => {
  try {
    const { schoolName } = req.body;
    const id = req.params.id;
    
    if (!schoolName) {
      return res.status(400).json({ success: false, message: 'School name is required' });
    }
    
    // Check for duplicate school with same name (excluding current record)
    const isDuplicate = await School.checkDuplicateByNameExcludingId(schoolName, id);
    if (isDuplicate) {
      return res.status(409).json({ success: false, message: 'A school with this name already exists' });
    }
    
    const affectedRows = await School.updateSchool(id, schoolName);
    
    if (affectedRows === 0) {
      return res.status(404).json({ success: false, message: 'School not found' });
    }
    
    res.status(200).json({ success: true, message: 'School updated successfully' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Failed to update school' });
  }
};

/* DELETE SCHOOL */
exports.deleteSchool = async (req, res) => {
  try {
    const affectedRows = await School.deleteSchool(req.params.id);
    
    if (affectedRows === 0) {
      return res.status(404).json({ success: false, message: 'School not found' });
    }
    
    res.status(200).json({ success: true, message: 'School deleted successfully' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, message: 'Failed to delete school' });
  }
};
