const db = require('../config/db');

/* GET ALL COURSES BY SCHOOL ID WITH INTERN COUNT */
exports.getCoursesBySchoolId = async (schoolId) => {
  const [rows] = await db.execute(`
    SELECT c.id, c.course_name, c.abbreviation, c.created_at, c.updated_at, 
           COUNT(i.id) as intern_count 
    FROM course c 
    LEFT JOIN intern i ON c.id = i.course_id 
    WHERE c.school_id = ?
    GROUP BY c.id, c.course_name, c.abbreviation, c.created_at, c.updated_at
  `, [schoolId]);
  return rows;
};

/* GET ALL COURSES WITH INTERN COUNT */
exports.getAllCoursesWithInternCount = async () => {
  const [rows] = await db.execute(`
    SELECT c.id, c.course_name, c.abbreviation, c.created_at, c.updated_at, 
           COUNT(i.id) as intern_count 
    FROM course c 
    LEFT JOIN intern i ON c.id = i.course_id 
    GROUP BY c.id, c.course_name, c.abbreviation, c.created_at, c.updated_at
  `);
  return rows;
};

/* GET COURSE BY ID WITH INTERN COUNT */
exports.getCourseByIdWithInternCount = async (id) => {
  const [rows] = await db.execute(`
    SELECT c.*, COUNT(i.id) as intern_count 
    FROM course c 
    LEFT JOIN intern i ON c.id = i.course_id 
    WHERE c.id = ?
    GROUP BY c.id
  `, [id]);
  return rows[0];
};

/* CHECK DUPLICATE BY NAME AND SCHOOL */
exports.checkDuplicateByName = async (courseName, schoolId) => {
  const [rows] = await db.execute(
    'SELECT id FROM course WHERE LOWER(course_name) = LOWER(?) AND school_id = ?',
    [courseName, schoolId]
  );
  return rows.length > 0;
};

/* CHECK DUPLICATE BY NAME AND SCHOOL EXCLUDING ID */
exports.checkDuplicateByNameExcludingId = async (courseName, schoolId, excludeId) => {
  const [rows] = await db.execute(
    'SELECT id FROM course WHERE LOWER(course_name) = LOWER(?) AND school_id = ? AND id != ?',
    [courseName, schoolId, excludeId]
  );
  return rows.length > 0;
};

/* CREATE - created_at is auto-generated by database, updated_at is NULL */
exports.createCourse = async (courseName, abbreviation, schoolId) => {
  const [result] = await db.execute(
    'INSERT INTO course (course_name, abbreviation, school_id, updated_at) VALUES (?, ?, ?, NULL)',
    [courseName, abbreviation, schoolId],
  );
  return result.insertId;
};

/* UPDATE / EDIT - update course name and set updated_at to current timestamp */
exports.updateCourse = async (id, courseName, abbreviation) => {
  const [result] = await db.execute(
    'UPDATE course SET course_name = ?, abbreviation = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?',
    [courseName, abbreviation, id],
  );
  return result.affectedRows;
};

/* DELETE */
exports.deleteCourse = async (id) => {
  const [result] = await db.execute('DELETE FROM course WHERE id = ?', [id]);
  return result.affectedRows;
};
