const db = require('../config/db');

/* READ ALL */
exports.getAllSchools = async () => {
  const [rows] = await db.execute('SELECT id, school_name, created_at, updated_at FROM school');
  return rows;
};

/* READ ONE */
exports.getSchoolById = async (id) => {
  const [rows] = await db.execute('SELECT * FROM school WHERE id = ?', [id]);
  return rows[0];
};

/* CHECK DUPLICATE BY NAME */
exports.checkDuplicateByName = async (schoolName) => {
  const [rows] = await db.execute(
    'SELECT id FROM school WHERE LOWER(school_name) = LOWER(?)',
    [schoolName]
  );
  return rows.length > 0;
};

/* CHECK DUPLICATE BY NAME EXCLUDING ID */
exports.checkDuplicateByNameExcludingId = async (schoolName, excludeId) => {
  const [rows] = await db.execute(
    'SELECT id FROM school WHERE LOWER(school_name) = LOWER(?) AND id != ?',
    [schoolName, excludeId]
  );
  return rows.length > 0;
};

/* CREATE - created_at is auto-generated by database, updated_at is NULL */
exports.createSchool = async (schoolName) => {
  const [result] = await db.execute(
    'INSERT INTO school (school_name, updated_at) VALUES (?, NULL)',
    [schoolName],
  );
  return result.insertId;
};

/* UPDATE / EDIT - update school name and set updated_at to current timestamp */
exports.updateSchool = async (id, schoolName) => {
  const [result] = await db.execute(
    'UPDATE school SET school_name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?',
    [schoolName, id],
  );
  return result.affectedRows;
};

/* DELETE */
exports.deleteSchool = async (id) => {
  const [result] = await db.execute('DELETE FROM school WHERE id = ?', [id]);
  return result.affectedRows;
};
